// Bumps the patch version on every build (e.g. 1.0.0 -> 1.0.1).
//
// Source of truth is package.json "version". This script increments the patch
// number, writes it back, and regenerates src/lib/version.ts which the footer
// imports. Wired into the build:* npm scripts so a build always advances the
// version shown in the app footer.

import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const root = process.cwd();
const pkgPath = join(root, 'package.json');
const versionTsPath = join(root, 'src', 'lib', 'version.ts');

const pkg = JSON.parse(await readFile(pkgPath, 'utf8'));

const parts = String(pkg.version ?? '0.0.0').split('.');
const major = Number(parts[0]) || 0;
const minor = Number(parts[1]) || 0;
const patch = Number(parts[2]) || 0;
const prev = `${major}.${minor}.${patch}`;
const next = `${major}.${minor}.${patch + 1}`;

pkg.version = next;
await writeFile(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);

const versionTs =
  `// AUTO-GENERATED by scripts/bump-version.mjs on each build — do not edit by hand.\n` +
  `export const APP_VERSION = '${next}';\n`;
await writeFile(versionTsPath, versionTs);

console.log(`[bump-version] ${prev} -> ${next}`);
